version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: test_nginx

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./app:/var/www/
    depends_on:
      - db
    container_name: test_app
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

  db:
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8182:3306"
    container_name: test_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    container_name: test_myadmin

